apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      component: redis
  template:
    metadata:
      labels:
        component: redis
    spec:
      volumes:
        - name: redis-storage
          persistentVolumeClaim:
            claimName: redis-pvc    
      containers:
        - name: redis
          image: redis/redis-stack:6.2.2-v4
          resources:
            limits:
              cpu: "10m"
              memory: "20Mi"
            requests:
              cpu: "5m"
              memory: "5Mi"
          ports:
          - containerPort: 6379
          volumeMounts:
            - mountPath: /data
              name: redis-storage
---
apiVersion: v1
kind: Service
metadata:
  name: redis-cluster-ip-service
spec:
  type: ClusterIP
  selector:
    component: redis
  ports:
    - name: tcp
      port: 6379
      targetPort: 6379
    - name: http
      port: 8001
      targetPort: 8001
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
